### ISSUE TITLE
Time_entry start time incorrect if duration updated past current time via API 

### ISSUE THREAD

**Issue by TILVince** [arendjantetteroo/guzzle-toggl#12]
I'm not sure whether this is a guzzle-toggl issue or a Toggl API issue.  Even if it's an unlikely occurrence, it obviously can happen.

I was testing the time_entry API calls, specifically to make sure my PHP code that translates duration into quarter hours worked correctly.  First, I manually created a Toggl timer within the Toggl web UI.  Then, via the API, I manipulated the duration of that time entry to extend the duration.  What I found was that the API (via the GetTimeEntries call) then reported the "start" time of the time_entry as the time at which the time_entry *would have* stopped, given the duration.  The extension of the duration put the end time into the future (i.e., with a time_entry start time of 11:09pm and duration of five hours, running the GetTimeEntries call at 11:15pm the API reported back that the start time was 4:09am the next morning -- five hours before the actual start time).

Thereafter, even if I used the API (via the UpdateTimeEntry call) to modify the start date of the time_entry to be days in the past, the start time via API would still report 4:09am even on the earlier date, while the Toggl UI shows the correct start time of 11:09pm.

BTW: I suppose I could have used the API to create a time_entry in the past, and then manipulate its duration in order to test my quarter-hour translation, but that's not our use-case;  We will use the Toggl web UI or Toggl app to create time_entries, and then pull the time_entries into our PHP app.

Thx,
Vince

**Comment by arendjantetteroo** [comment]
Hi Vince,

It sounds like something the toggl api is doing, as there is no logic in the guzzle toggl package. It just pipes what you put in into the api, and pipes what it gets out to your script. If something is wrong in the service description this might go wrong, but otherwise this sounds like something on Toggl's end. 

Can you provide a gist so i can try it out?

**Comment by TILVince** [comment]
Thanks, but I'm not going to worry with it. As mentioned, I was just testing another part of my code that calculates quarter hours from the Toggl duration.  Rather than manipulating one time entry several times to test different scenarios, I should have just used the API to create timers of varying duration to test those scenarios.  In my production app, I don't really have a need to manipulate the duration through the API after a timer has been created.

Thanks for the offer.  I figured it might be something in the API itself.

Vince
