### ISSUE TITLE
Create User problem

### ISSUE THREAD

**Issue by jcyusupov** [arendjantetteroo/guzzle-toggl#13]
Hello! I have a problem with API. When I try to create new user - always receive same error message:
Client error response
[status code] 400
[reason phrase] Bad Request
[url] https://www.toggl.com/api/v8/signups

My code:
$this->api->createUser([
            'email' => $user->email,
            'password' => '123123123',
        ]);

Also I tried : 
$this->api->createUser([
            'user' => [ 
                    'email' => $user->email,
                    'password' => '123123123',
            ]
        ]);

Standart cURL command work fine, but API no. 

Also, API doesn't have command for invaite users to workspace.
Can you help me with it?

Thank you.

**Comment by arendjantetteroo** [comment]
Can you make a gist i can try? 

I'm open to pull requests for the invite users to workspace method.

**Comment by jcyusupov** [comment]
https://gist.github.com/jcyusupov/d3ea33e7fec378fd145d#file-gistfile1-php
It's my gist.

Thank you!
