### ISSUE TITLE
Not able to pull time entries via API

### ISSUE THREAD

**Issue by drkapoor** [arendjantetteroo/guzzle-toggl#28]
Hi

I really need your help. I'm struggling with getting time entries on Toggl via API.

I am working on a Laravel based project and I need to import time entries from my Toggl account. I am not able to pull records via API for some reason. I have configured the library correctly as per the given instructions.

![image (1)](https://user-images.githubusercontent.com/50033861/62908201-a7ebc280-bd2b-11e9-9a26-014982d276c7.png)

It should retrieve the records from Toggl and print a JSON on the browser. But I am getting below error message on every request to API.
GuzzleHttp \ Exception \ ClientException (403) Client error: GET https://toggl.com/api/v8/time_entries?user_agent=deepak%40gmail.com&workspace_id=257895&with_related_data=1 resulted in a 403 Forbidden response

Please have a look into this and shed some light on this and let us know if this is a known issue and how should we resolve this?

Thanks,
Deepak

**Comment by arendjantetteroo** [comment]
I don't see my package used in your code? 

Are you sure the workspace_id is correct?
