### ISSUE TITLE
Update API Url Domain to api.track.toggl.com

### ISSUE THREAD

**Issue by gilberthdez** [arendjantetteroo/guzzle-toggl#29]
toggl.com or www.toggl.com will no longer be a supported entry point for the Toggl Track API check:
- https://github.com/toggl/toggl_api_docs
- https://toggl.com/blog/api-documentation-change

**Comment by arendjantetteroo** [comment]
Thanks @gilberthdez . can you make a pull request to change it?

**Comment by gilberthdez** [comment]
sorry, I haven't touched PHP in years 😅 (just here helping out notifying that the current implementation using www.toggl.com will be not supported soonish :) )

**Comment by arendjantetteroo** [comment]
Closed by #30
