### ISSUE TITLE
Report Project Dashboard Support

### ISSUE THREAD

**Issue by tlannom-nni** [arendjantetteroo/guzzle-toggl#31]
Hello! I am using your library but needed support for the report project dashboard. I forked your repo & made the update & wanted to check to see if you were interested in getting a pull request for it? It is a paid account feature only so I wasn't sure if you were trying to keep your lib to only free options.

Here is the api call I'm referencing: https://github.com/toggl/toggl_api_docs/blob/master/reports/project.md

Also unrelated question (sorry if I should create a new issue for this), are there any plans for Guzzle 7 support upcoming since 6 is on security updates only? If not I will make plans to work on that in the future but my team isn't familiar with Guzzle so it's an unknown level effort for us so thought I would check in case it's on deck already.

Thank you for your lib, it's been extremely useful!

**Comment by arendjantetteroo** [comment]
@tlannom-nni Hey, welcome. glad you find it useful. Feel free to open a pull request, i don't have a policy for only free, just want to have a useful library for people to use. 

With regards to guzzle 7, i don't currently have plans, at the moment i don't use this library myself, just try to keep it maintained by merging pull requests from others. 
I'm not sure how big the changes are between 6 and 7, i'll see if i can give you some pointers.

**Comment by arendjantetteroo** [comment]
@tlannom-nni please check my PR at #32 for an upgrade to guzzle7. If you can let me know if this works for you, i'll merge it to master and tag a new release for it.

**Comment by tlannom-nni** [comment]
@arendjantetteroo Thank you so much!! I will get this in my teams sprint next week and confirm with you asap! And I'll get you that pull request for our update tomorrow.

**Comment by tlannom-nni** [comment]
@arendjantetteroo If this change looks good, could you please either merge or rebase your guzzle7 branch with this update for our testing of the guzzle7 updates?

**Comment by arendjantetteroo** [comment]
@tlannom-nni done, check the guzzle7 branch.

**Comment by tlannom-nni** [comment]
@arendjantetteroo Thank you so much! I didn't expect such fast turn around time so thank you again! I'm sneaking this into one of my devs schedule today to test & verify, I'll have an update for you soon!

**Comment by tlannom-nni** [comment]
@arendjantetteroo We have confirmed that the guzzle 7 updates are working! You're all good to push those updates. Thank you again for your help and fast response rate, especially for a project you don't even use anymore! :D

**Comment by arendjantetteroo** [comment]
Thanks. 

Tagged both v1.2.0 with the report update and v.1.3.0 with guzzle7. 
https://github.com/arendjantetteroo/guzzle-toggl/releases/tag/v.1.3.0
