### ISSUE TITLE
New release for packagist

### ISSUE THREAD

**Issue by akhumphrey** [arendjantetteroo/guzzle-toggl#34]
Can you please provide new releases for packagist? Both the v1.2.0 and the v1.3.0 releases are unavailable to install via composer at this time.

As an aside, would it be possible to implement automatic updates to packagist so you don't need to manually do it every time?

**Comment by arendjantetteroo** [comment]
@akhumphrey thanks, i've reconnected my accounts to packagist, i assume this should appear soon. I'll keep an eye on it today.

**Comment by arendjantetteroo** [comment]
@akhumphrey it's good now. It seems i made a mistake in the tags, there was an extra . after the v which it didn't accept. I retagged a 1.2.1 as the fixed v1.2.0 now pointed at master. 

Thanks for pointing it out.
