### ISSUE TITLE
API v9 support

### ISSUE THREAD

**Issue by edward-simpson** [arendjantetteroo/guzzle-toggl#43]
v8 API has now been disabled, so this client no longer works

**Comment by Echron** [comment]
@edward-simpson it seems this package is not maintained anymore. I'm looking into https://github.com/ixudra/toggl as alternative.

**Comment by edward-simpson** [comment]
@Echron true, the v8->9 changes aren't hugely complex though, I've got a local branch with it working, tempted to PR it back in

**Comment by edward-simpson** [comment]
@Echron although I've only really tested it with the clients list API, and don't really have the time to thoroughly test it with others

**Comment by Echron** [comment]
@edward-simpson, if you have it working, I would suggest creating a PR. 

I don't have time to make the change in this client, so I opted to switch to a client who has already upgraded to v9. A PR to a dev branch would already be a huge step to update this client, and if you need help making further changes and testing the changes, let me know. 

Given that @arendjantetteroo thinks this is an ok plan, of course.

**Comment by arendjantetteroo** [comment]
Hi, sorry i totally missed this. I don't use toggl myself anymore, but am open to a PR.

**Comment by edward-simpson** [comment]
Draft PR #44 , draft for reasons mentioned in the PR

**Comment by ericmerrill** [comment]
While I don't know how useful it is, since I don't use many functions in TogglClient, I was able to use the #44 PR to get my project working. Only change I had to make was moving the id param to workspace_id in getProjects as described.
Thanks for this @edward-simpson!

**Comment by Echron** [comment]
Tested and workes fine for me. 

@edward-simpson does this need more work? Can I help with anything?

@arendjantetteroo, if everything is met, shall we create a new version? At the moment, this module is useless sadly, so better to move on with this one and make sure people using it are not moving away.

**Comment by arendjantetteroo** [comment]
Thanks for confirming @Echron and @ericmerrill  :) 

I'll tag a new release asap.

**Comment by Echron** [comment]
@arendjantetteroo Was gonna lock my project to v2 but I see it's not available in Composer yet (https://packagist.org/packages/ajt/guzzle-toggl). 
Packagist page says it was updated yesterday. 
Also, I noticed on the main branch in composer.json that the version is set to 9.0.0. So it might be related to this: https://github.com/composer/packagist/issues/587#issuecomment-317645837

I've now locked to dev-main in composer to test everything out and it everything seems to work. Great work

**Comment by arendjantetteroo** [comment]
Forgot to change that before merging the PR. I've now tagged a 2.0.1 
https://github.com/arendjantetteroo/guzzle-toggl/releases/tag/v2.0.1

I'll check on packagist to see if it will appear now. 

dev-main should work in the mean time.

**Comment by arendjantetteroo** [comment]
Ok, 2.0.1 is there now aftere removing the composer.json version. Thanks for the helpful link @Echron 

https://packagist.org/packages/ajt/guzzle-toggl
