### ISSUE TITLE
Upgrade to Guzzle 5/6

### ISSUE THREAD

**Issue by arendjantetteroo** [arendjantetteroo/guzzle-toggl#9]

**Comment by Arrisar** [comment]
I'd be happy to look at contributing this via a PR. For reference, is all the Guzzle related code in one place (e.g. the factory)?

**Comment by arendjantetteroo** [comment]
The whole service description system needs to be changed to use something like this : 
https://github.com/guzzle/guzzle-services

Possibly might even be simpler to start over based on guzzle 6 then trying to upgrade to 4 then 5 then 6. 
Unfortunately i don' thave time to look into this, i'm open to PR's though.

**Comment by DragosMocrii** [comment]
+1

**Comment by arendjantetteroo** [comment]
Fixed by #22 . Thanks @Echron
